version: '3'

services:
  db:
    image: mongo:7.0.1
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db

  ui:
    build:
      context: ./chat-ui
      secrets:
        - DOTENV_LOCAL
    ports:
      - "7860:3000"
    depends_on:
      - db

  tgi:
    image: ghcr.io/huggingface/text-generation-inference:1.0.3
    ports:
      - "8080:3000"
    volumes:
      - ${PWD}/data:/data
    env_file:
      - tgi.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  mongo-data:


secrets:
  DOTENV_LOCAL:
    file: .env.local
